project:
  type: website
  output-dir: docs
  preview: 
    port: 3931

website:
  title: "ling343demosite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - mynewpage.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



